### ISSUE TITLE
User can view a table

### ISSUE THREAD

**Issue by vorleakyek** [vorleakyek/BoredNoMore#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view a table of sample suggested activities for all types of activities

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user visits the homepage, they should be able to view a table of top suggested activities.  

Notes: 
- Maybe 25-50 activities 
- Show 25 activities per page 
- Can click on the next button to show the next 25 activities   

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

https://www.figma.com/file/Cu29I1ZiHUh8BnH0sGq3sS/Vorleak-Yek---AJAX-Project?type=design&node-id=1%3A4&mode=design&t=p2pDbp0PHgTG24Tv-1 

## ✅ Task List
> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create the HTML for the homepage header for the mobile device first.
- [x] Below the header, create the HTML for the Top Activities section.
- [x] Create the table and table header 
- [x] Fetch a list of activities from the  API using this doc https://www.boredapi.com/documentation. 
- [x] Store about 25 - 50 activities in an array. 
- [x] Loop through the array to get the value of these properties
   - [x] activity
   - [x] accessibility
   - [x] type
   - [x] participants
   - [x] price 
- [x] for each iteration in the loop 
   - [x]   append each value to each cell of the table row accordingly 
- [x] Use CSS to style the table as in the wireframe  
- [x] Switch to Desktop mode and adjust the layout based on the wireframe. 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
