### ISSUE TITLE
User can search an activity 

### ISSUE THREAD

**Issue by vorleakyek** [vorleakyek/BoredNoMore#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can search for different activities based on the activity type.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on the search bar, they should be able to type and search for the activity. The list activities that matches should be display on the table. The rest will be hidden from the table. 
If no match is found, then there should be a text display “No match is found!”  
Users can search across the activity and type columns. If either the activity or type is matched, return the list of activities. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

https://www.figma.com/file/Cu29I1ZiHUh8BnH0sGq3sS/Vorleak-Yek---AJAX-Project?type=design&node-id=1%3A4&mode=design&t=p2pDbp0PHgTG24Tv-1 
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the search bar 
- [x] Style it using CSS 
- [x] Make sure the page layout works well on both desktop and mobile 
- [x] Get the input value that the user has typed in the search bar and store it as a variable 
- [x] Use the Array.find() and other methods needed to search for the matched values
- [x] store those matched object in an array 
- [x] Make sure to account for both Activity and types columns 
- [x] Clear the current table cells 
- [x] replace the cells with the activity/type that matches the search criteria
- [x]  If no data is matching the search criteria, display a text ‘No match is found.’ 
- [x] After clearing search, the original table should be displayed 
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
