### ISSUE TITLE
User can filter activities

### ISSUE THREAD

**Issue by vorleakyek** [vorleakyek/BoredNoMore#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can filter activities based on activity type.  

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can filter out the type of activities using the filter button and check the option they want. Only the matching result should be displayed on the table. Users can also clear the filter by removing the filter pill buttons. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
https://www.figma.com/file/Cu29I1ZiHUh8BnH0sGq3sS/Vorleak-Yek---AJAX-Project?type=design&node-id=1-4&mode=design&t=w822hkmwTzsXgQHH-0

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML for the filter button 
- [x] Create a modal for the filter option 
- [ ] Create filter pillar buttons for each checked value type
- [x] Style it using CSS 
- [x] Make sure the page layout works well on both desktop and mobile 
- [x] Retrieve the values that are checked from the modal and store in an array when the popup is closed
- [x] Use the Array.filter() method to filter out the matched conditions 
- [x] Clear the current table cells
- [x] Replace the cells with the type that matches the filter criteria
- [ ] Display the filter pills based on the checked values
- [x] Updating the table accordingly after each type is removed
- [x] After clearing all the filter conditions, the original table should be displayed
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
