### ISSUE TITLE
User can generate a random activity 

### ISSUE THREAD

**Issue by vorleakyek** [vorleakyek/BoredNoMore#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can generate a random activity from the API. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When users click on the "Generate" button, it should display a random activity on the page. The activity is generating from all types and it is from the API itself. So, it might not be on the top activity table. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML for the random generator section 
- [x] Style it as in the wireframe 
- [x] Make sure page layout is good for both mobile and desktop 
- [x] Fetch a random activity from the Bored API when clicking on the "Generate" button  
- [x] Save the result object in a variable 
- [x] display the info based on the result 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
